---
title: "Publications"
# output:
#   html_document:
#     highlight: haddock
#     theme: cerulean
#     toc: no
#   pdf_document:
#     toc: no
#   word_document:
#     toc: no
---

See my [Google Scholar profile](https://scholar.google.com/citations?user=W8mU7s8AAAAJ&hl=en) for up to date publication list with citation counts.

* Simmons, B. A., Butt, N., __O’Hara, C. C.__, Ray, R., Yang, H., Ma, Y., Ma, X., Gallagher, K. P. (draft).  Mapping the risks of China’s global coastal development to marine socio-ecological systems.
* __O’Hara, C. C.__, & Halpern, B. S. (2022). [Anticipating the Future of the World’s Ocean. Annual Review of Environment and Resources, 47(1), annurev-environ-120120-053645.](https://doi.org/10.1146/annurev-environ-120120-053645)
* Butt, N., Halpern, B. S., __O’Hara, C. C.__, Allcock, A. L., Polidoro, B., Sherman, S., Byrne, M., Birkeland, C., Dwyer, R. G., Frazier, M., Woodworth, B. K., Arango, C. P., Kingsford, M. J., Udyawer, V., Hutchings, P., Scanes, E., McClaren, E. J., Maxwell, S. M., Diaz-Pulido, G., … Klein, C. J. (2022). [A trait-based framework for assessing the vulnerability of marine species to human impacts. Ecosphere, 13(2), e3919.](https://doi.org/10.1002/ecs2.3919)
* __O’Hara, C. C.__, Frazier, M., & Halpern, B. S. (2021). [At-risk marine biodiversity faces extensive, expanding, and intensifying human impacts. Science, 372(6537), 84–87](https://doi.org/10.1126/science.abe6731). 
* Roberson, L. A., Beyer, H. L., __O’Hara, C.__, Watson, J. E. M., Dunn, D. C., Halpern, B. S., Klein, C. J., Frazier, M. R., Kuempel, C. D., Williams, B., Grantham, H. S., Montgomery, J. C., Kark, S., & Runting, R. K. (2021). [Multinational coordination required for conservation of over 90% of marine species. Global Change Biology, 27(23), 6206–6216](https://doi.org/10.1111/gcb.15844).
* Beck, M. W., __O’Hara, C. C.__, Lowndes, J. S. S., Mazor, R. D., Theroux, S., Gillett, D. J., Lane, B., & Gearheart, G. (2020). [The importance of open science for biological assessment of aquatic environments. PeerJ, 8, e9539.](https://doi.org/10.7717/peerj.9539)
* __O’Hara, C. C.__, Scarborough, C., Hunter, K. L., Afflerbach, J. C., Bodtker, K., Frazier, M., Lowndes, J. S. S., Perry, R. I., & Halpern, B. S. (2020). [Changes in ocean health in British Columbia from 2001 to 2016. PLOS ONE, 15(1), e0227502.](https://doi.org/10.1371/journal.pone.0227502)
* Friedman, W. R., Halpern, B. S., McLeod, E., Beck, M. W., Duarte, C. M., Kappel, C. V., Levine, A., Sluka, R. D., Adler, S., __O’Hara, C. C.__, Sterling, E. J., Tapia-Lewin, S., Losada, I. J., McClanahan, T. R., Pendleton, L., Spring, M., Toomey, J. P., Weiss, K. R., Possingham, H. P., & Montambault, J. R. (2020). [Research Priorities for Achieving Healthy Marine Ecosystems and Human Communities in a Changing Climate. Frontiers in Marine Science, 7.](https://doi.org/10.3389/fmars.2020.00005)
* Halpern, B. S., Frazier, M., Afflerbach, J., Lowndes, J. S., Micheli, F., __O’Hara, C. C.__, Scarborough, C., & Selkoe, K. A. (2019). [Recent pace of change in human impact on the world’s ocean. Scientific Reports, 9(1), 1–8.](https://doi.org/10.1038/s41598-019-47201-9)
* Burgass, M. J., Milner-Gulland, E. J., Stewart Lowndes, J. S., __O’Hara, C. C.__, Afflerbach, J. C., & Halpern, B. S. (2018). [A pan-Arctic assessment of the status of marine social-ecological systems. Regional Environmental Change.](https://doi.org/10.1007/s10113-018-1395-6)
* __O’Hara, C. C.__, Villaseñor‐Derbez, J. C., Ralph, G. M., & Halpern, B. S. (2019). [Mapping status and conservation of global at‐risk marine biodiversity. Conservation Letters, e12651.](https://doi.org/10.1111/conl.12651)
* Halpern, B. S., Frazier, M., Afflerbach, J., __O’Hara, C. C.__, Katona, S., Stewart Lowndes, J. S., Jiang, N., Pacheco, E., Scarborough, C., & Polsenberg, J. (2017). [Drivers and implications of change in global ocean health over the past five years. PLOS ONE, 12(7), e0178267.](https://doi.org/10.1371/journal.pone.0178267)
* Lowndes, J. S. S., Best, B. D., Scarborough, C., Afflerbach, J. C., Frazier, M. R., __O’Hara, C. C.__, Jiang, N., & Halpern, B. S. (2017). [Our path to better science in less time using open data science tools. Nature Ecology & Evolution, 1(6), 0160.](https://doi.org/10.1038/s41559-017-0160)
* __O’Hara, C. C.__, Afflerbach, J. C., Scarborough, C., Kaschner, K., & Halpern, B. S. (2017). [Aligning marine species range data to better serve science and conservation. PLOS ONE, 12(5), e0175739.](https://doi.org/10.1371/journal.pone.0175739)

