---
title: "At-risk marine biodiversity faces extensive, expanding, and intensifying human impacts"
description: |
author:
  - name: "Casey C. O’Hara, Melanie Frazier, Benjamin S. Halpern"
date: "April 3, 2021"
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Human activities and climate change threaten marine biodiversity worldwide, though sensitivity to these stressors varies considerably by species and taxonomic group. Mapping the spatial distribution of
14 anthropogenic stressors from 2003 to 2013 onto the ranges of 1271 at-risk marine species sensitive to them, we found that, on average, species faced potential impacts across 57% of their ranges, that this footprint expanded over time, and that the impacts intensified across 37% of their ranges. Although fishing activity dominated the footprint of impacts in national waters, climate stressors drove the expansion and intensification of impacts. Mitigating impacts on at-risk biodiversity is critical to supporting resilient marine ecosystems, and identifying the co-occurrence of impacts across multiple taxonomic groups highlights opportunities to amplify the benefits of conservation management.

